// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADaHcGiL7qFic_4y6hxNxYNEAcM22xY1o',
    appId: '1:36058659857:web:6d7568a098988a7ccc85b0',
    messagingSenderId: '36058659857',
    projectId: 'lifetracker-b35f7',
    authDomain: 'lifetracker-b35f7.firebaseapp.com',
    storageBucket: 'lifetracker-b35f7.firebasestorage.app',
    measurementId: 'G-P13R5TCJ4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg1FpsEXDeBnN9eFB9iTl83pPPIr8d-1s',
    appId: '1:36058659857:android:d388b7262a05111bcc85b0',
    messagingSenderId: '36058659857',
    projectId: 'lifetracker-b35f7',
    storageBucket: 'lifetracker-b35f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xi-PW3dFP63imIkgt0UsJO6sQ2IdEU0',
    appId: '1:36058659857:ios:6a5aa5f9d7ab6f41cc85b0',
    messagingSenderId: '36058659857',
    projectId: 'lifetracker-b35f7',
    storageBucket: 'lifetracker-b35f7.firebasestorage.app',
    iosBundleId: 'com.example.lifetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xi-PW3dFP63imIkgt0UsJO6sQ2IdEU0',
    appId: '1:36058659857:ios:6a5aa5f9d7ab6f41cc85b0',
    messagingSenderId: '36058659857',
    projectId: 'lifetracker-b35f7',
    storageBucket: 'lifetracker-b35f7.firebasestorage.app',
    iosBundleId: 'com.example.lifetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADaHcGiL7qFic_4y6hxNxYNEAcM22xY1o',
    appId: '1:36058659857:web:2d9be36f0a5b2f5ccc85b0',
    messagingSenderId: '36058659857',
    projectId: 'lifetracker-b35f7',
    authDomain: 'lifetracker-b35f7.firebaseapp.com',
    storageBucket: 'lifetracker-b35f7.firebasestorage.app',
    measurementId: 'G-WNKKYH9E46',
  );
}
